#!/bin/sh

# Copy small .ops file to mimic APS files for background concentrations
# call: cpall compname (so2, nox, nh3)

if [ "$1" == "" ]
then
   echo " call: cpall compname (lower case so2, nox, nh3)"
   exit
fi

FIRSTYEAR=1977
OVERLAPYEAR=2018  # from this year on we have an overlap of chem_meteo_actual and chem_meteo_prognosis
FUTUREYEAR=2022
ENDYEAR=2030

# File names to copy from (_nf3 means 3 fields):
fnam=template3x2.ops
fnam3=template3x2_nf3.ops
cmp=$1
cmp_upper=$(echo "$cmp" | tr '[:lower:]' '[:upper:]')
if [ "$cmp_upper" == "NOX" ]
then
   cmp_upper=NOx
fi
echo $cmp_upper
 
# Background concentration files for reference years:
for year in 1984 1994 2005 2012 2018 
do
   echo ${year}
   cp $fnam ../chem_meteo_actual/bg${cmp}c${year}.ops
done

# Background concentration files for years starting at OVERLAPYEAR:
echo "========================================="
#year=$FUTUREYEAR
year=$OVERLAPYEAR
while [ ${year} -le $ENDYEAR ]
do
   echo ${year}
   cp $fnam ../chem_meteo_prognosis/bg${cmp}c${year}.ops
   year=$(expr ${year} '+' 1)
done

# EMEP files starting from 2014:
echo "========================================="
year=2014
while [ ${year} -le $ENDYEAR ]
do
   echo ${year}

   if [ ${year} -lt $FUTUREYEAR ]
   then
      cp $fnam ../chem_meteo_actual/${cmp_upper}_mass_prec_${year}.ops
      cp $fnam ../chem_meteo_actual/${cmp_upper}_mass_conv_dtfac_${year}.ops
      cp $fnam3 ../chem_meteo_actual/no3_distr_${year}.ops
   fi
   if [ ${year} -ge $OVERLAPYEAR ]
   then
      cp $fnam ../chem_meteo_prognosis/${cmp_upper}_mass_prec_${year}.ops
      cp $fnam ../chem_meteo_prognosis/${cmp_upper}_mass_conv_dtfac_${year}.ops
      cp $fnam3 ../chem_meteo_prognosis/no3_distr_${year}.ops
   fi
   year=$(expr ${year} '+' 1)
done

